# Movie Recommendation Project
## Introduction
In the vast landscape of entertainment, finding the perfect movie to watch can be a daunting task. To address this challenge, I have developed a Movie Recommendation project that leverages three powerful recommendation methods: `Popularity-Based Filtering`, `Content-Based Filtering`, and `Collaborative Filtering`.

## Objective
The primary goal of this project is to provide users with personalized movie recommendations based on their preferences, using a combination of different filtering techniques.

## Methods
### Popularity-Based Filtering:
This method recommends movies based on their overall popularity among all users. The recommendation score is calculated using the **Weighted Rating Formula**:

\[WR = (v / (v + m)) * R + (m + (v + m)) * C \]

where:
- \( v \) is the number of votes for the movie.
- \( m \) is the minimum votes required to be listed.
- \( R \) is the average rating of the movie.
- \( C \) is the mean rating across all movies.

This is a simple yet effective approach that gives higher weight to movies with higher ratings and more votes.

### Content-Based Filtering:
Content-Based Filtering recommends movies by analyzing the content and features of each movie. This method takes into account user preferences and suggests movies with similar characteristics to those the user has enjoyed in the past.

### Collaborative Filtering:
Collaborative Filtering identifies patterns in user behavior and recommends movies based on the preferences of users with similar tastes. For this, the project utilizes the [Surprise](http://surpriselib.com/) library, a Python scikit for building and analyzing recommender systems.

The specific modules used for collaborative filtering are:
- [Dataset](https://surprise.readthedocs.io/en/stable/dataset.html) from Surprise: A module to load a dataset.
- [Reader](https://surprise.readthedocs.io/en/stable/reader.html) from Surprise: A module to define the format of the input file.
- [SVD (Singular Value Decomposition)](https://surprise.readthedocs.io/en/stable/matrix_factorization.html#surprise.prediction_algorithms.matrix_factorization.SVD) from Surprise: A collaborative filtering algorithm based on matrix factorization.
- [model_selection](https://surprise.readthedocs.io/en/stable/model_selection.html) from Surprise: A module providing tools for model selection and evaluation.

## Implementation
The project is implemented in a Jupyter Notebook, utilizing Python and the following data science libraries:

- [Pandas](https://pandas.pydata.org/): A powerful and easy-to-use data manipulation and analysis library.
- [NumPy](https://numpy.org/): The fundamental package for scientific computing with Python.
- [scikit-learn](https://scikit-learn.org/stable/): A machine learning library that provides simple and efficient tools for data analysis and modeling.

For content-based filtering, the project uses the [linear_kernel](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise.linear_kernel.html) from scikit-learn. The dataset used for training and testing the recommendation models is sourced from [mention the dataset source].

## <span style="color:#004d80">Popularity-Based Filtering</span>

### Importing Panda Library

In [21]:
import pandas as pd

In [22]:
movies = pd.read_csv('movies.csv')

In [23]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [24]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

### Calculate a weighted rating

WR = (v / (v + m)) * R + (m + (v + m)) * C

v - number of votes for a movie <br>
m - minimum number of votes required<br>
R - average rating of votes required<br>
C - average rating across all movies

In [25]:
m = movies['vote_count'].quantile(0.9) # 0.9 -> 90%
m

1838.4000000000015

* that means 90% of the movies have vote count less than `1838.40` and 10% of movies have a vote count of higher than `1838.40`

In [26]:
C = movies['vote_average'].mean()
C

6.092171559442016

In [27]:
popularity_movies = movies.copy()

In [32]:
def weighted_rating(df, m=m,C=C):
    
    """
    Calculate the weighted rating for each movie using the given formula.

    Parameters:
    - df (DataFrame): DataFrame containing movie information.
    - m (float): Minimum votes required for a movie to be considered.
    - C (float): Mean rating across all movies.

    Returns:
    - Series: Series containing the calculated 'weighted_rating' for each movie.
    """
    # Extract relevant columns
    R = df['vote_average']
    v = df['vote_count']
    
    # Apply the weighted rating formula
    wr = (v / (v + m)) * R + (m + (v + m)) * C
    
    return wr

In [33]:
popularity_movies['weighted_rating'] = popularity_movies.apply(weighted_rating, axis=1)

In [34]:
popularity_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,weighted_rating
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,94293.550261
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,49819.367120
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,49611.797457
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,77881.333990
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,35342.738618

In [35]:
# Sorting movies by 'weighted_rating' in descending order and selecting the top 10.
popularity_movies.sort_values('weighted_rating', ascending=False)[['title','weighted_rating']].head(10)

                       title  weighted_rating
96                 Inception    106186.384534
65           The Dark Knight     95525.050252
0                     Avatar     94293.550261
16              The Avengers     94147.509426
788                 Deadpool     89389.462627
95              Interstellar     88610.252702
287         Django Unchained     83931.135742
94   Guardians of the Galaxy     81756.277589
426         The Hunger Games     80006.955265
127       Mad Max: Fury Road     79836.622713

### <span style="color:red">Conclusion for Popularity-Based Filtering

* The Popularity-Based Filtering method was employed to recommend movies based on their overall popularity. The weighted rating formula, considering both the average rating and the number of votes, was utilized to prioritize movies that not only received high ratings but also garnered a substantial number of votes.

* The top 10 movies recommended by this approach, as displayed above, showcase the most popular and well-received movies according to the weighted rating criterion. Users looking for widely acclaimed and widely watched movies can refer to this list for their next cinematic experience.
    
    
    
<br><br><br>

## <span style="color:#004d80">Content Based Filtering
* focus on `overview` column

In [36]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

### Text Feature Extraction using TF-IDF Vectorizer

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
tfidf = TfidfVectorizer(stop_words='english')

In [39]:
movies['overview']=movies['overview'].fillna('')

In [40]:
tfidf_matrix = tfidf.fit_transform(movies['overview'])

In [41]:
# Convert TF-IDF Matrix to Pandas DataFrame
pd.DataFrame(tfidf_matrix.toarray(), columns=tfidf.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zuckerberg,zula,zuzu,zyklon,æon,éloigne,émigré,été,única,über
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [42]:
tfidf_matrix.shape

(4803, 20978)

### Similarity matrix

In [43]:
# Import Linear Kernel for Similarity Calculation
from sklearn.metrics.pairwise import linear_kernel

In [44]:
similarity_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [45]:
similarity_matrix

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.02160533, 0.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.01488159, 0.        ,
        0.        ],
       ...,
       [0.        , 0.02160533, 0.01488159, ..., 1.        , 0.01609091,
        0.00701914],
       [0.        , 0.        , 0.        , ..., 0.01609091, 1.        ,
        0.01171696],
       [0.        , 0.        , 0.        , ..., 0.00701914, 0.01171696,
        1.        ]])

In [46]:
similarity_matrix.shape

(4803, 4803)

### Find the most similar movies to a certain movie

In [47]:
def similar_movies(movie_title, nr_movies):
    """
    Get a list of similar movies based on the cosine similarity between movie vectors.

    Parameters:
    - movie_title (str): The title of the movie for which similar movies are to be found.
    - nr_movies (int): The number of similar movies to retrieve.

    Returns:
    - List[str]: A list of titles of similar movies.
    """
    # Find the index of the movie in the DataFrame
    idx = movies.loc[movies['title']==movie_title].index[0]
    
    # Get the similarity scores for the given movie
    scores = list(enumerate(similarity_matrix[idx]))
    
    # Sort the movies based on similarity scores in descending order
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    
    # Extract the indices of similar movies (excluding the input movie)
    movies_indices = [tpl[0] for tpl in scores[1:nr_movies+1]]
    
    # Get the titles of similar movies
    similar_titles = list(movies['title'].iloc[movies_indices])
    
    return similar_titles

In [48]:
similar_movies('The Dark Knight',3)

['The Dark Knight Rises',
 'Batman Returns',
 'Batman: The Dark Knight Returns, Part 2']

### <span style="color:red">Conclusion for Content-Based Filtering</span>

* Content-Based Filtering, implemented through the `similar_movies` function, employs cosine similarity scores based on TF-IDF vectors to recommend movies with similar content features to a given movie.

* In this demonstration, movies similar to 'The Dark Knight' have been identified, showcasing the capability of the Content-Based Filtering approach to provide personalized recommendations based on content characteristics.

* This method is particularly valuable for suggesting movies that share thematic elements, genres, or content features, delivering a personalized viewing experience aligned with the user's preferences.

    
<br><br><br>

## <span style="color:#004d80">Collaborative Filtering

In [50]:
ratings = pd.read_csv("ratings.csv")
ratings.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

### Create the dataset

In [51]:
# Importing Dataset and Reader classes from the Surprise library
from surprise import Dataset, Reader

In [52]:
# Creating a Reader instance with the rating scale defined as (1, 5)
reader = Reader(rating_scale=(1,5))

# Loading the dataset from the 'ratings' DataFrame using the specified Reader
dataset = Dataset.load_from_df(ratings[['userId','movieId','rating']],reader)
dataset

### Build the trainset

In [53]:
trainset = dataset.build_full_trainset()

In [54]:
list(trainset.all_ratings())

[(0, 0, 2.5),
 (0, 1, 3.0),
 (0, 2, 3.0),
 (0, 3, 2.0),
 (0, 4, 4.0),
 (0, 5, 2.0),
 (0, 6, 2.0),
 (0, 7, 2.0),
 (0, 8, 3.5),
 (0, 9, 2.0),
 (0, 10, 2.5),
 (0, 11, 1.0),
 (0, 12, 4.0),
 (0, 13, 4.0),
 (0, 14, 3.0),
 (0, 15, 2.0),
 (0, 16, 2.0),
 (0, 17, 2.5),
 (0, 18, 1.0),
 (0, 19, 3.0),
 (1, 20, 4.0),
 (1, 21, 5.0),
 (1, 22, 5.0),
 (1, 23, 4.0),
 (1, 24, 4.0),
 (1, 25, 3.0),
 (1, 26, 3.0),
 (1, 27, 4.0),
 (1, 28, 3.0),
 (1, 29, 5.0),
 (1, 30, 4.0),
 (1, 31, 3.0),
 (1, 32, 3.0),
 (1, 33, 3.0),
 (1, 34, 3.0),
 (1, 35, 3.0),
 (1, 36, 3.0),
 (1, 37, 5.0),
 (1, 38, 1.0),
 (1, 39, 3.0),
 (1, 40, 3.0),
 (1, 41, 3.0),
 (1, 42, 4.0),
 (1, 43, 4.0),
 (1, 44, 5.0),
 (1, 45, 5.0),
 (1, 46, 3.0),
 (1, 47, 4.0),
 (1, 48, 3.0),
 (1, 49, 4.0),
 (1, 50, 3.0),
 (1, 51, 4.0),
 (1, 52, 2.0),
 (1, 53, 1.0),
 (1, 54, 3.0),
 (1, 55, 4.0),
 (1, 56, 4.0),
 (1, 57, 3.0),
 (1, 58, 3.0),
 (1, 59, 3.0),
 (1, 60, 3.0),
 (1, 61, 2.0),
 (1, 62, 3.0),
 (1, 63, 3.0),
 (1, 64, 3.0),
 (1, 65, 3.0),
 (1, 66, 2.0),
 (1, 67, 3.0),
 (1, 68, 4.0),
 (1, 69, 3.0),
 (1, 70, 4.0),
 (1, 71, 2.0),
 (1, 72, 4.0),
 (1, 73, 3.0),
 (1, 74, 3.0),
 (1, 75, 4.0),
 (1, 76, 4.0),
 (1, 77, 4.0),
 (1, 78, 4.0),
 (1, 79, 4.0),
 (1, 80, 4.0),
 (1, 81, 3.0),
 (1, 82, 3.0),
 (1, 83, 5.0),
 (1, 84, 3.0),
 (1, 85, 5.0),
 (1, 86, 3.0),
 (1, 87, 3.0),
 (1, 88, 3.0),
 (1, 89, 5.0),
 (1, 90, 5.0),
 (1, 91, 5.0),
 (1, 92, 3.0),
 (1, 93, 3.0),
 (1, 94, 4.0),
 (1, 95, 4.0),
 (2, 96, 3.0),
 (2, 27, 4.0),
 (2, 97, 3.5),
 (2, 98, 3.0),
 (2, 49, 4.5),
 (2, 99, 5.0),
 (2, 100, 2.5),
 (2, 57, 5.0),
 (2, 64, 2.5),
 (2, 79, 3.0),
 (2, 88, 3.0),
 (2, 91, 3.0),
 (2, 92, 3.0),
 (2, 101, 2.0),
 (2, 102, 3.5),
 (2, 103, 4.0),
 (2, 104, 3.0),
 (2, 105, 5.0),
 (2, 106, 3.0),
 (2, 107, 4.0),
 (2, 108, 3.0),
 (2, 109, 4.0),
 (2, 110, 3.5),
 (2, 111, 4.5),
 (2, 112, 4.0),
 (2, 113, 4.0),
 (2, 114, 4.0),
 (2, 115, 3.0),
 (2, 116, 3.0),
 (2, 117, 3.5),
 (2, 118, 3.0),
 (2, 119, 3.5),
 (2, 120, 4.0),
 (2, 121, 4.0),
 (2, 122, 5.0),
 (2, 123, 3.0),
 (2, 124, 4.0),
 (2, 125, 5.0),
 (2, 126, 3.0),
 (2, 127, 3.5),
 (2, 128, 3.0),
 (2, 129, 2.5),
 (2, 130, 3.0),
 (2, 131, 3.5),
 (2, 132, 3.0),
 (2, 133, 3.5),
 (2, 134, 3.5),
 (2, 135, 4.5),
 (2, 136, 4.5),
 (2, 137, 3.0),
 (2, 138, 4.0),
 (3, 20, 4.0),
 (3, 139, 5.0),
 (3, 140, 5.0),
 (3, 141, 5.0),
 (3, 30, 4.0),
 (3, 142, 3.0),
 (3, 34, 3.0),
 (3, 143, 5.0),
 (3, 144, 4.0),
 (3, 49, 5.0),
 (3, 145, 3.0),
 (3, 55, 5.0),
 (3, 57, 5.0),
 (3, 58, 5.0),
 (3, 59, 5.0),
 (3, 60, 4.0),
 (3, 146, 3.0),
 (3, 67, 3.0),
 (3, 147, 3.0),
 (3, 148, 4.0),
 (3, 149, 1.0),
 (3, 150, 4.0),
 (3, 151, 4.0),
 (3, 152, 4.0),
 (3, 72, 5.0),
 (3, 153, 5.0),
 (3, 88, 5.0),
 (3, 89, 5.0),
 (3, 90, 3.0),
 (3, 154, 5.0),
 (3, 155, 5.0),
 (3, 156, 4.0),
 (3, 93, 5.0),
 (3, 157, 5.0),
 (3, 158, 5.0),
 (3, 159, 4.0),
 (3, 160, 5.0),
 (3, 161, 5.0),
 (3, 162, 4.0),
 (3, 163, 4.0),
 (3, 164, 5.0),
 (3, 165, 5.0),
 (3, 166, 5.0),
 (3, 167, 5.0),
 (3, 168, 5.0),
 (3, 169, 5.0),
 (3, 170, 5.0),
 (3, 171, 5.0),
 (3, 172, 5.0),
 (3, 173, 5.0),
 (3, 174, 5.0),
 (3, 175, 5.0),
 (3, 176, 5.0),
 (3, 177, 5.0),
 (3, 178, 5.0),
 (3, 179, 5.0),
 (3, 105, 5.0),
 (3, 180, 5.0),
 (3, 181, 5.0),
 (3, 182, 5.0),
 (3, 183, 5.0),
 (3, 106, 5.0),
 (3, 184, 5.0),
 (3, 185, 5.0),
 (3, 186, 5.0),
 (3, 187, 5.0),
 (3, 188, 5.0),
 (3, 189, 5.0),
 (3, 190, 5.0),
 (3, 191, 5.0),
 (3, 192, 5.0),
 (3, 193, 5.0),
 (3, 194, 5.0),
 (3, 195, 4.0),
 (3, 196, 5.0),
 (3, 197, 5.0),
 (3, 198, 5.0),
 (3, 199, 5.0),
 (3, 200, 4.0),
 (3, 201, 5.0),
 (3, 202, 5.0),
 (3, 203, 4.0),
 (3, 204, 4.0),
 (3, 205, 4.0),
 (3, 206, 5.0),
 (3, 207, 5.0),
 (3, 208, 4.0),
 (3, 10, 4.0),
 (3, 209, 3.0),
 (3, 210, 4.0),
 (3, 211, 3.0),
 (3, 212, 3.0),
 (3, 213, 5.0),
 (3, 214, 5.0),
 (3, 215, 4.0),
 (3, 216, 5.0),
 (3, 217, 3.0),
 (3, 110, 5.0),
 (3, 218, 4.0),
 (3, 219, 5.0),
 (3, 220, 1.0),
 (3, 221, 5.0),
 (3, 222, 4.0),
 (3, 223, 2.0),
 (3, 12, 5.0),
 (3, 224, 5.0),
 (3, 225, 5.0),
 (3, 226, 3.0),
 (3, 227, 5.0),
 (3, 228, 5.0),
 (3, 229, 5.0),
 (3, 230, 3.0),
 (3, 231, 2.0),
 (3, 232, 5.0),
 (3, 233, 4.0),
 (3, 234, 5.0),
 (3, 235, 4.0),
 (3, 236, 4.0),
 (3, 237, 4.0),
 (3, 238, 4.0),
 (3, 239, 5.0),
 (3, 240, 3.0),
 (3, 241, 5.0),
 (3, 242, 5.0),
 (3, 243, 5.0),
 (3, 244, 4.0),
 (3, 245, 5.0),
 (3, 246, 5.0),
 (3, 247, 5.0),
 (3, 248, 5.0),
 (3, 249, 4.0),
 (3, 250, 5.0),
 (3, 251, 5.0),
 (3, 252, 5.0),
 (3, 13, 4.0),
 (3, 253, 5.0),
 (3, 254, 3.0),
 (3, 255, 5.0),
 (3, 256, 5.0),
 (3, 257, 4.0),
 (3, 258, 5.0),
 (3, 259, 4.0),
 (3, 260, 4.0),
 (3, 261, 5.0),
 (3, 262, 5.0),
 (3, 263, 5.0),
 (3, 15, 3.0),
 (3, 264, 5.0),
 (3, 265, 4.0),
 (3, 266, 3.0),
 (3, 267, 5.0),
 (3, 268, 5.0),
 (3, 269, 4.0),
 (3, 270, 4.0),
 (3, 271, 4.0),
 (3, 272, 5.0),
 (3, 273, 4.0),
 (3, 274, 5.0),
 (3, 275, 5.0),
 (3, 276, 4.0),
 (3, 277, 1.0),
 (3, 278, 5.0),
 (3, 279, 5.0),
 (3, 280, 3.0),
 (3, 281, 4.0),
 (3, 282, 4.0),
 (3, 118, 5.0),
 (3, 283, 5.0),
 (3, 284, 4.0),
 (3, 285, 1.0),
 (3, 286, 5.0),
 (3, 287, 5.0),
 (3, 288, 4.0),
 (3, 289, 5.0),
 (3, 290, 5.0),
 (3, 291, 3.0),
 (3, 292, 3.0),
 (3, 293, 5.0),
 (3, 294, 5.0),
 (3, 295, 2.0),
 (3, 296, 1.0),
 (3, 297, 4.0),
 (3, 298, 5.0),
 (3, 18, 5.0),
 (3, 299, 3.0),
 (3, 300, 5.0),
 (3, 301, 5.0),
 (3, 302, 3.0),
 (3, 303, 5.0),
 (3, 304, 4.0),
 (3, 305, 5.0),
 (3, 306, 5.0),
 (3, 307, 4.0),
 (3, 308, 4.0),
 (3, 309, 4.0),
 (3, 310, 5.0),
 (3, 311, 4.0),
 (3, 312, 2.0),
 (3, 313, 4.0),
 (3, 314, 5.0),
 (3, 315, 4.0),
 (3, 316, 3.0),
 (3, 317, 5.0),
 (3, 318, 2.0),
 (4, 319, 4.0),
 (4, 22, 4.0),
 (4, 320, 4.0),
 (4, 141, 4.0),
 (4, 29, 4.0),
 (4, 321, 3.5),
 (4, 322, 4.5),
 (4, 323, 3.5),
 (4, 57, 4.0),
 (4, 59, 4.0),
 (4, 60, 4.0),
 (4, 64, 4.0),
 (4, 150, 4.0),
 (4, 75, 4.5),
 (4, 86, 4.0),
 (4, 88, 3.5),
 (4, 101, 4.0),
 (4, 324, 5.0),
 (4, 325, 3.5),
 (4, 157, 2.5),
 (4, 158, 3.5),
 (4, 161, 4.0),
 (4, 164, 4.0),
 (4, 326, 5.0),
 (4, 327, 3.0),
 (4, 328, 2.5),
 (4, 329, 4.0),
 (4, 204, 4.0),
 (4, 213, 5.0),
 (4, 330, 3.5),
 (4, 331, 4.5),
 (4, 217, 3.5),
 (4, 332, 4.0),
 (4, 111, 4.0),
 (4, 333, 4.0),
 (4, 334, 4.5),
 (4, 335, 4.5),
 (4, 225, 4.0),
 (4, 227, 4.0),
 (4, 336, 3.5),
 (4, 337, 1.5),
 (4, 244, 5.0),
 (4, 338, 4.0),
 (4, 16, 4.0),
 (4, 339, 3.5),
 (4, 340, 4.0),
 (4, 341, 3.5),
 (4, 281, 4.0),
 (4, 116, 4.5),
 (4, 342, 4.0),
 (4, 119, 3.5),
 (4, 285, 3.5),
 (4, 298, 3.5),
 (4, 343, 3.5),
 (4, 344, 3.5),
 (4, 345, 3.5),
 (4, 346, 4.0),
 (4, 347, 3.5),
 (4, 348, 4.5),
 (4, 349, 3.5),
 (4, 350, 4.0),
 (4, 351, 4.0),
 (4, 352, 3.5),
 (4, 353, 4.5),
 (4, 354, 3.5),
 (4, 355, 3.5),
 (4, 356, 4.5),
 (4, 357, 3.5),
 (4, 358, 3.0),
 (4, 359, 4.5),
 (4, 360, 3.5),
 (4, 361, 4.5),
 (4, 126, 4.5),
 (4, 362, 4.0),
 (4, 127, 3.5),
 (4, 363, 4.5),
 (4, 364, 3.0),
 (4, 365, 4.0),
 (4, 366, 3.5),
 (4, 367, 4.0),
 (4, 128, 4.0),
 (4, 368, 4.0),
 (4, 369, 2.5),
 (4, 370, 4.0),
 (4, 371, 4.0),
 (4, 372, 4.0),
 (4, 131, 3.5),
 (4, 132, 4.5),
 (4, 373, 4.0),
 (4, 374, 4.5),
 (4, 375, 4.5),
 (4, 376, 3.5),
 (4, 377, 5.0),
 (4, 378, 4.0),
 (4, 379, 4.5),
 (4, 380, 4.0),
 (4, 381, 4.5),
 (4, 382, 4.0),
 (4, 383, 4.0),
 (4, 384, 4.5),
 (5, 385, 4.0),
 (5, 386, 2.0),
 (5, 142, 2.0),
 (5, 387, 5.0),
 (5, 155, 4.0),
 (5, 158, 4.0),
 (5, 388, 5.0),
 (5, 389, 4.5),
 (5, 195, 4.5),
 (5, 390, 4.5),
 (5, 200, 4.5),
 (5, 391, 2.0),
 (5, 392, 2.0),
 (5, 393, 2.0),
 (5, 394, 2.0),
 (5, 395, 0.5),
 (5, 396, 3.0),
 (5, 397, 3.0),
 (5, 398, 4.0),
 (5, 399, 4.0),
 (5, 263, 4.0),
 (5, 341, 3.5),
 (5, 400, 3.0),
 (5, 401, 4.0),
 (5, 402, 1.0),
 (5, 403, 2.0),
 (5, 404, 4.0),
 (5, 283, 3.0),
 (5, 405, 4.5),
 (5, 406, 3.0),
 (5, 407, 1.0),
 (5, 344, 4.0),
 (5, 408, 3.5),
 (5, 409, 1.5),
 (5, 410, 1.5),
 (5, 411, 1.5),
 (5, 412, 5.0),
 (5, 413, 3.0),
 (5, 129, 5.0),
 (5, 130, 4.0),
 (5, 414, 3.5),
 (5, 132, 4.0),
 (5, 415, 3.0),
 (5, 416, 4.5),
 (6, 417, 3.0),
 (6, 20, 3.0),
 (6, 418, 3.0),
 (6, 0, 3.0),
 (6, 139, 4.0),
 (6, 419, 4.0),
 (6, 320, 3.0),
 (6, 27, 5.0),
 (6, 140, 4.0),
 (6, 141, 4.0),
 (6, 420, 4.0),
 (6, 421, 2.0),
 (6, 422, 3.0),
 (6, 143, 5.0),
 (6, 46, 3.0),
 (6, 423, 2.0),
 (6, 99, 5.0),
 (6, 145, 3.0),
 (6, 424, 3.0),
 (6, 425, 3.0),
 (6, 100, 3.0),
 (6, 57, 3.0),
 (6, 58, 3.0),
 (6, 59, 3.0),
 (6, 60, 3.0),
 (6, 64, 3.0),
 (6, 146, 4.0),
 (6, 72, 4.0),
 (6, 75, 3.0),
 (6, 426, 4.0),
 (6, 81, 3.0),
 (6, 153, 4.0),
 (6, 83, 4.0),
 (6, 88, 4.0),
 (6, 89, 3.0),
 (6, 90, 4.0),
 (6, 91, 3.0),
 (6, 154, 4.0),
 (6, 101, 3.0),
 (6, 156, 3.0),
 (6, 427, 4.0),
 (6, 428, 3.0),
 (6, 95, 5.0),
 (6, 429, 2.0),
 (6, 102, 1.0),
 (6, 430, 1.0),
 (6, 431, 5.0),
 (6, 432, 3.0),
 (6, 433, 2.0),
 (6, 434, 4.0),
 (6, 170, 3.0),
 (6, 171, 3.0),
 (6, 172, 4.0),
 (6, 435, 4.0),
 (6, 174, 3.0),
 (6, 175, 3.0),
 (6, 3, 3.0),
 (6, 177, 4.0),
 (6, 436, 5.0),
 (6, 179, 5.0),
 (6, 105, 3.0),
 (6, 180, 5.0),
 (6, 106, 5.0),
 (6, 187, 4.0),
 (6, 437, 5.0),
 (6, 189, 5.0),
 (6, 438, 4.0),
 (6, 191, 4.0),
 (6, 439, 5.0),
 (6, 197, 3.0),
 (6, 440, 4.0),
 (6, 198, 3.0),
 (6, 6, 4.0),
 (6, 201, 4.0),
 (6, 202, 3.0),
 (6, 203, 3.0),
 (6, 441, 4.0),
 (6, 204, 3.0),
 (6, 442, 3.0),
 (6, 10, 3.0),
 (6, 209, 3.0),
 (6, 443, 2.0),
 (6, 210, 4.0),
 (6, 444, 3.0),
 (6, 211, 3.0),
 (6, 445, 3.0),
 (6, 11, 5.0),
 (6, 446, 1.0),
 (7, 447, 5.0),
 (7, 448, 2.5),
 (7, 23, 5.0),
 (7, 24, 5.0),
 (7, 27, 4.0),
 (7, 143, 3.5),
 (7, 449, 2.0),
 (7, 49, 4.0),
 (7, 99, 5.0),
 (7, 57, 4.0),
 (7, 69, 4.5),
 (7, 450, 3.5),
 (7, 451, 2.0),
 (7, 79, 5.0),
 (7, 452, 5.0),
 (7, 89, 4.0),
 (7, 92, 4.5),
 (7, 453, 4.0),
 (7, 454, 3.5),
 (7, 157, 5.0),
 (7, 179, 3.5),
 (7, 105, 4.0),
 (7, 180, 4.0),
 (7, 106, 4.0),
 (7, 186, 4.0),
 (7, 189, 4.0),
 (7, 194, 4.0),
 (7, 195, 4.0),
 (7, 196, 3.0),
 (7, 197, 4.0),
 (7, 202, 4.0),
 (7, 441, 3.5),
 (7, 391, 0.5),
 (7, 214, 4.0),
 (7, 330, 3.0),
 (7, 455, 4.0),
 (7, 456, 3.0),
 (7, 457, 3.5),
 (7, 458, 5.0),
 (7, 219, 4.0),
 (7, 459, 4.0),
 (7, 460, 3.0),
 (7, 333, 5.0),
 (7, 395, 3.5),
 (7, 225, 5.0),
 (7, 113, 4.0),
 (7, 251, 3.0),
 (7, 461, 3.0),
 (7, 264, 4.5),
 (7, 462, 4.5),
 (7, 463, 4.0),
 (7, 464, 5.0),
 (7, 465, 3.5),
 (7, 466, 3.5),
 (7, 341, 5.0),
 (7, 402, 5.0),
 (7, 118, 3.5),
 (7, 119, 4.5),
 (7, 285, 2.5),
 (7, 287, 4.5),
 (7, 289, 3.5),
 (7, 290, 3.5),
 (7, 120, 3.0),
 (7, 121, 4.5),
 (7, 298, 5.0),
 (7, 122, 4.0),
 (7, 467, 4.5),
 (7, 468, 5.0),
 (7, 469, 3.5),
 (7, 349, 4.0),
 (7, 470, 4.0),
 (7, 471, 4.5),
 (7, 472, 3.5),
 (7, 473, 4.5),
 (7, 474, 5.0),
 (7, 475, 4.0),
 (7, 476, 2.5),
 (7, 477, 3.5),
 (7, 478, 3.5),
 (7, 358, 4.5),
 (7, 479, 4.0),
 (7, 480, 3.5),
 (7, 359, 3.5),
 (7, 481, 5.0),
 (7, 482, 3.5),
 (7, 483, 4.5),
 (7, 362, 4.0),
 (7, 484, 4.0),
 (7, 485, 4.0),
 (7, 127, 3.0),
 (7, 412, 4.0),
 (7, 486, 3.5),
 (7, 128, 4.0),
 (7, 487, 3.0),
 (7, 488, 4.0),
 (7, 489, 5.0),
 (7, 490, 3.0),
 (7, 491, 3.5),
 (7, 129, 4.0),
 (7, 130, 4.0),
 (7, 492, 4.0),
 (7, 493, 2.5),
 (7, 415, 4.5),
 (7, 494, 4.0),
 (7, 416, 3.0),
 (7, 495, 3.5),
 (7, 377, 4.5),
 (7, 496, 4.5),
 (7, 497, 4.5),
 (7, 379, 3.5),
 (7, 498, 3.5),
 (7, 381, 3.5),
 (7, 499, 2.0),
 (7, 500, 3.5),
 (7, 501, 3.0),
 (7, 502, 3.0),
 (8, 417, 4.0),
 (8, 21, 4.0),
 (8, 503, 3.0),
 (8, 504, 5.0),
 (8, 23, 3.0),
 (8, 99, 4.0),
 (8, 74, 4.0),
 (8, 78, 4.0),
 (8, 79, 5.0),
 (8, 426, 5.0),
 (8, 92, 4.0),
 (8, 505, 5.0),
 (8, 506, 2.0),
 (8, 507, 5.0),
 (8, 508, 3.0),
 (8, 509, 4.0),
 (8, 391, 4.0),
 (8, 510, 3.0),
 (8, 511, 2.0),
 (8, 512, 4.0),
 (8, 513, 4.0),
 (8, 332, 5.0),
 (8, 459, 4.0),
 (8, 111, 3.0),
 (8, 334, 5.0),
 (8, 113, 4.0),
 (8, 514, 4.0),
 (8, 258, 4.0),
 (8, 515, 4.0),
 (8, 267, 3.0),
 (8, 338, 3.0),
 (8, 516, 4.0),
 (8, 517, 4.0),
 (8, 16, 2.0),
 (8, 462, 4.0),
 (8, 518, 4.0),
 (8, 519, 4.0),
 (8, 520, 2.0),
 (8, 521, 3.0),
 (8, 522, 4.0),
 (8, 523, 2.0),
 (8, 402, 5.0),
 (8, 278, 3.0),
 (8, 119, 4.0),
 (8, 524, 4.0),
 (9, 24, 5.0),
 (9, 525, 4.0),
 (9, 99, 4.0),
 (9, 323, 3.0),
 (9, 425, 4.0),
 (9, 91, 3.0),
 (9, 526, 4.0),
 (9, 170, 3.0),
 (9, 173, 3.0),
 (9, 527, 2.0),
 (9, 176, 4.0),
 (9, 179, 4.0),
 (9, 105, 4.0),
 (9, 180, 4.0),
 (9, 181, 4.0),
 (9, 106, 4.0),
 (9, 187, 3.0),
 (9, 191, 4.0),
 (9, 202, 4.0),
 (9, 391, 5.0),
 (9, 528, 4.0),
 (9, 529, 3.0),
 (9, 530, 3.0),
 (9, 531, 5.0),
 (9, 532, 3.0),
 (9, 459, 4.0),
 (9, 533, 5.0),
 (9, 534, 2.0),
 (9, 335, 5.0),
 (9, 535, 3.0),
 (9, 536, 5.0),
 (9, 272, 4.0),
 (9, 537, 2.0),
 (9, 523, 4.0),
 (9, 402, 5.0),
 (9, 538, 5.0),
 (9, 539, 3.0),
 (9, 540, 3.0),
 (9, 120, 4.0),
 (9, 541, 3.0),
 (9, 406, 4.0),
 (9, 542, 2.0),
 (9, 543, 5.0),
 (9, 544, 2.0),
 (9, 545, 3.0),
 (9, 546, 4.0),
 (10, 24, 5.0),
 (10, 547, 1.0),
 (10, 548, 4.0),
 (10, 549, 3.0),
 (10, 49, 5.0),
 (10, 103, 4.5),
 (10, 550, 3.5),
 (10, 551, 5.0),
 (10, 552, 4.5),
 (10, 553, 5.0),
 (10, 446, 5.0),
 (10, 223, 3.0),
 (10, 554, 3.5),
 (10, 555, 4.5),
 (10, 119, 3.0),
 (10, 556, 3.0),
 (10, 127, 3.0),
 (10, 557, 5.0),
 (10, 558, 5.0),
 (10, 559, 5.0),
 (10, 560, 4.0),
 (10, 561, 4.5),
 (10, 562, 3.5),
 (10, 563, 4.5),
 (10, 564, 4.0),
 (10, 565, 4.5),
 (10, 566, 3.0),
 (10, 567, 4.0),
 (10, 568, 3.5),
 (10, 569, 4.0),
 (10, 570, 4.5),
 (10, 571, 4.5),
 (10, 572, 4.0),
 (10, 573, 4.0),
 (10, 574, 4.0),
 (10, 575, 4.0),
 (10, 576, 5.0),
 (10, 577, 5.0),
 (11, 42, 3.0),
 (11, 578, 1.0),
 (11, 579, 3.0),
 (11, 505, 2.0),
 (11, 580, 1.0),
 (11, 102, 4.0),
 (11, 430, 3.0),
 (11, 165, 1.0),
 (11, 168, 2.0),
 (11, 581, 3.0),
 (11, 105, 1.0),
 (11, 582, 5.0),
 (11, 187, 5.0),
 (11, 190, 2.0),
 (11, 107, 5.0),
 (11, 583, 1.0),
 (11, 210, 1.0),
 (11, 214, 4.0),
 (11, 392, 2.0),
 (11, 584, 3.0),
 (11, 585, 2.0),
 (11, 339, 2.0),
 (11, 586, 4.0),
 (11, 401, 1.0),
 (11, 587, 2.0),
 (11, 122, 4.0),
 (11, 588, 2.0),
 (11, 589, 1.0),
 (11, 345, 3.0),
 (11, 590, 2.0),
 (11, 591, 4.0),
 (11, 592, 1.0),
 (11, 346, 4.0),
 (11, 593, 4.0),
 (11, 594, 3.0),
 (11, 595, 2.0),
 (11, 596, 2.0),
 (11, 597, 1.0),
 (11, 598, 5.0),
 (11, 599, 3.0),
 (11, 600, 4.0),
 (11, 601, 1.0),
 (11, 602, 3.0),
 (11, 603, 3.0),
 (11, 604, 5.0),
 (11, 605, 2.0),
 (11, 606, 2.0),
 (11, 607, 4.0),
 (11, 608, 2.0),
 (11, 609, 1.0),
 (11, 610, 3.0),
 (11, 611, 5.0),
 (11, 612, 3.0),
 (11, 613, 5.0),
 (11, 614, 2.0),
 (11, 615, 2.0),
 (11, 616, 3.0),
 (11, 617, 5.0),
 (11, 618, 3.0),
 (11, 619, 2.0),
 (11, 620, 4.0),
 (12, 417, 5.0),
 (12, 23, 2.5),
 (12, 27, 4.0),
 (12, 322, 4.0),
 (12, 49, 3.5),
 (12, 99, 4.5),
 (12, 57, 5.0),
 (12, 621, 4.5),
 (12, 72, 3.0),
 (12, 451, 3.5),
 (12, 79, 4.0),
 (12, 622, 4.0),
 (12, 87, 3.0),
 (12, 90, 4.0),
 (12, 623, 4.0),
 (12, 161, 3.5),
 (12, 552, 3.0),
 (12, 195, 4.0),
 (12, 196, 2.5),
 (12, 223, 3.0),
 (12, 225, 4.0),
 (12, 339, 4.0),
 (12, 402, 3.0),
 (12, 624, 3.5),
 (12, 405, 4.0),
 (12, 119, 3.0),
 (12, 290, 3.0),
 (12, 625, 3.0),
 (12, 298, 3.0),
 (12, 344, 3.0),
 (12, 467, 4.0),
 (12, 315, 3.5),
 (12, 626, 3.5),
 (12, 627, 3.0),
 (12, 354, 4.0),
 (12, 628, 4.5),
 (12, 629, 2.5),
 (12, 357, 3.5),
 (12, 630, 4.5),
 (12, 477, 3.5),
 (12, 480, 4.5),
 (12, 486, 4.0),
 (12, 128, 4.5),
 (12, 130, 4.0),
 (12, 631, 4.5),
 (12, 632, 3.5),
 (12, 137, 4.5),
 (12, 633, 4.5),
 (12, 634, 4.0),
 (12, 635, 4.0),
 (12, 636, 4.5),
 (12, 637, 4.5),
 (12, 638, 3.0),
 (13, 154, 1.0),
 (13, 179, 4.0),
 (13, 111, 3.0),
 (13, 639, 3.0),
 (13, 339, 2.0),
 (13, 640, 3.0),
 (13, 278, 3.0),
 (13, 281, 2.0),
 (13, 118, 3.0),
 (13, 641, 2.0),
 (13, 642, 3.0),
 (13, 643, 2.0),
 (13, 344, 4.0),
 (13, 644, 2.0),
 (13, 645, 5.0),
 (13, 646, 3.0),
 (13, 647, 3.0),
 (13, 409, 4.0),
 (13, 648, 3.0),
 (13, 649, 4.0),
 (14, 417, 2.0),
 (14, 650, 2.0),
 (14, 651, 4.5),
 (14, 652, 4.0),
 (14, 20, 3.0),
 (14, 653, 2.5),
 (14, 654, 2.5),
 (14, 655, 3.5),
 (14, 21, 3.0),
 (14, 656, 1.0),
 (14, 418, 4.5),
 (14, 657, 2.5),
 (14, 658, 3.0),
 (14, 447, 4.0),
 (14, 139, 3.0),
 (14, 504, 1.0),
 (14, 22, 2.5),
 (14, 659, 3.0),
 (14, 23, 5.0),
 (14, 24, 5.0),
 (14, 25, 2.5),
 (14, 26, 2.0),
 (14, 547, 0.5),
 (14, 660, 5.0),
 (14, 661, 3.0),
 (14, 662, 1.5),
 (14, 663, 4.0),
 (14, 320, 1.0),
 (14, 664, 2.0),
 (14, 27, 3.0),
 (14, 385, 5.0),
 (14, 140, 2.5),
 (14, 665, 4.0),
 (14, 666, 3.5),
 (14, 667, 3.5),
 (14, 668, 5.0),
 (14, 29, 3.0),
 (14, 30, 1.0),
 ...]

### Train the Model

In [55]:
from surprise import SVD

In [56]:
svd = SVD()

In [57]:
svd.fit(trainset)

In [58]:
# Making a prediction for user with ID 15 and item with ID 1956
svd.predict(15,1956)

Prediction(uid=15, iid=1956, r_ui=None, est=3.3127737105813835, details={'was_impossible': False})

* The `est` field in the output represents the estimated rating for the given user-item pair.

### Validation

In [59]:
from surprise import model_selection

In [60]:
# Using cross-validation to evaluate the SVD model's performance on the dataset
model_selection.cross_validate(svd,dataset,measures=['RMSE','MAE'])

{'test_rmse': array([0.89213304, 0.89616525, 0.89376161, 0.9000934 , 0.90307484]),
 'test_mae': array([0.68682168, 0.69086371, 0.68845708, 0.69360254, 0.69470127]),
 'fit_time': (1.518972396850586,
  1.2473247051239014,
  1.220029354095459,
  1.2253117561340332,
  1.2086174488067627),
 'test_time': (0.5035138130187988,
  0.18817400932312012,
  0.18307781219482422,
  0.18808746337890625,
  0.16300082206726074)}

* RMSE: An RMSE of around 0.89 implies that, on average, the predicted ratings differ from the true ratings by approximately 0.89 units. This could be considered acceptable, depending on the scale of your ratings.

* MAE: An MAE of around 0.69 means that, on average, the absolute difference between predicted and true ratings is approximately 0.69. Again, this depends on the scale of your ratings, but a lower MAE is generally desirable.

### <span style="color:red">Conclusion for Collaborative Filtering</span>

* Collaborative Filtering, implemented through the Surprise library and the SVD algorithm, leverages user-item interaction patterns to make personalized movie recommendations.

* The SVD model was trained on the provided dataset, and cross-validation results indicate reasonably good performance with RMSE values around 0.89 and MAE values around 0.69. However, the assessment should be considered in the context of the specific characteristics and requirements of the recommendation system and dataset.

* It's crucial to recognize that the effectiveness of collaborative filtering depends on the availability and quality of user-item interactions. Sparse data, user-item cold-start problems, and the scalability of the model to large datasets should be taken into consideration.

* Collaborative Filtering excels in capturing latent features and uncovering user preferences based on their interactions. It offers a valuable approach for providing personalized recommendations, particularly when content-based information is limited.